#!/usr/bin/env bash

export PASSWORD_STORE_DIR="$HOME/.password-store"

list_passwords() {
  find $PASSWORD_STORE_DIR -type f ! -path "*.git*" -printf '%P\n'|sed s'|.gpg$||'
}

if [ "$#" -ne 0 ]
then
    pass $*
else
    PASSWORD_FILE="$(list_passwords|fzf)"
    echo "login: $(basename "$PASSWORD_FILE")"
    if command -v wl-copy > /dev/null 2>&1; then
      pass $PASSWORD_FILE |wl-copy
    else
      pass $PASSWORD_FILE
    fi
fi
