#!/usr/bin/env bash

PASSWORD_STORE_DIR="$HOME/.password-store"
CACHE=~/.local/tmp/pass_wofi

list_passwords() {
    shopt -s nullglob globstar
  cd "${PASSWORD_STORE_DIR}" || exit
  pw_list=(**/*.gpg)
  printf '%s\n' "${pw_list[@]%.gpg}" | sort -n
}

prompt='search for passwords...'
SECRET=$(list_passwords | wofi -i --prompt="${prompt}" --dmenu --cache-file ${CACHE})

PASSWD_PASS=$(pass ${SECRET})

wl-copy -o ${PASSWD_PASS}
